### ISSUE TITLE
Session Length Chart GA -> Dasheroo

### ISSUE THREAD

**Issue by lisaratner** [lisaratner/long-beach-analytics#110]

**Comment by lisaratner** [comment]
@rossettistone I created a board on dasheroo called ROI if you want to put session length there. Thanks!

**Comment by rossettistone** [comment]
As Dasheroo does not provide an out-of-the-box Session Duration chart, I've reached out to their support for suggestions in how we might build one. It's possible to use BizPort as a proxy for this data (GA->BizPort->Dasheroo), but this is much bigger lift, so I want to confirm that there's no other way before going that route.

**Comment by rossettistone** [comment]
Unhelpful response from Dasheroo support:
"Unfortunately, we don't have any GA session duration insight yet, however, I will get this in front of the product team for consideration as a possible future enhancement. A product manager may reach back out to you for more input as this makes it way to our feature enhancement roadmap.

Thanks for the feedback, and keep it coming!"

Another metric we can try to proxy through BizPort, though that's considerably greater lift than I had hoped. Gonna move this back to the backlog for the time being.

**Comment by lisaratner** [comment]
option: upgrade zapier and zap GA to Google Sheets to Dasheroo

**Comment by lisaratner** [comment]
ping Heidi if you need i-team login info and credit card number

**Comment by lisaratner** [comment]
@rossettistone Hey Mark, is this what we decided, upgrade to zapier and zap GA session length data to Google sheets which then connects to Dasheroo?

**Comment by rossettistone** [comment]
Yep, I think that's the way to go. We can of course build/test this without
upgrading the Zapier account just yet, but I think it's the best plan at
this point.

**Comment by rossettistone** [comment]
Session length remains interesting, but Dasheroo is dying, so this is on hold until we find the new analytics dashboard platform.

**Comment by rossettistone** [comment]
Dasheroo is now defunct. Closing.
