### ISSUE TITLE
Spec for dashboarding tool

### ISSUE THREAD

**Issue by rossettistone** [lisaratner/long-beach-analytics#128]
As we move to a new tool to replace Dasheroo, we'll need a clear spec of what features and graphs are important so that we can judge the efficacy of any new solution.

**Comment by lisaratner** [comment]
Necessary:
Connect to Google Analytics, Google Sheets, Zapier
Package qualitative data nicely (pulling from Google Sheets)
Embed entire dashboard into a website
Ability to subscribe to the dashboard

Nice to Have:
Connect to Intercom and Typeform directly without Zapier
Commenting
Alerts

**Comment by lisaratner** [comment]
https://docs.google.com/document/d/1VBSx2YTOA_MSKeViyFuU66MwD-DZCs3-WUkb2TqCVCs/edit?usp=sharing
