### ISSUE TITLE
Curate email verbiage

### ISSUE THREAD

**Issue by heidiwiersma** [lisaratner/long-beach-analytics#86]
Lisa, I  (Heidi) need your help remembering what exactly I'm trying to accomplish with this verbiage. Thanks!

**Comment by lisaratner** [comment]
@heidiwiersma I took a stab at the verbiage. Do you mind adding your 2 cents? Thank you!

Dear Long Beach Business Owner,
We are working hard to improve our process in working with entrepreneurs and current business owners. We have piloted a website to be a resource and need your feedback to know what areas need improvement so we can meet your needs. There is a help / chat icon in the bottom corner of our website where you can send us your comments: BizPort.LongBeach.gov

We also have a survey to better understand your experience and how we did in helping you get your business up: http://bizport.longbeach.gov/survey.

If you know anyone that has closed a business in Long Beach, do you mind forwarding them this survey so we can better understand why they closed their doors and identify how we can help prevent closures: bit.ly/closing_biz

Thank you for your time and insight,
City of Long Beach
LongBeach@CodeforAmerica.org

**Comment by lisaratner** [comment]
When you have an edited version you like. Do you mind sharing it with Brett for sign-off on Thursday?
Much appreciated,
Lisa
