### ISSUE TITLE
Account Migration

### ISSUE THREAD

**Issue by lisaratner** [lisaratner/long-beach-analytics#94]
Mark will chat with Scott about SAS subscriptions
Dasheroo Account $19 / mo
Typeform Account ? / mo
Intercom Account $25 / mo

**Comment by lisaratner** [comment]
@rossettistone do you mind updating the status from your Scott convo here?

@heidiwiersma it sounds like I should at least migrate Dasheroo over to you

**Comment by rossettistone** [comment]
Yep! The conclusion from the meeting was that SaaS products (like Dasheroo and Typeform) in the City are managed and paid for by either 1) advance purchase order (if the vendor offers such a service) or 2) the owner of the product, on a reimbursement basis. 

I agree that it would make sense to transfer ownership to Heidi.

**Comment by heidiwiersma** [comment]
@lisaratner and @rossettistone we can go ahead and start migrating things over to the i-team, I ask that we use i-team@longbeach.gov as the email on each of the accounts. That way it doesn't come down to any one person.

**Comment by lisaratner** [comment]
@heidiwiersma wonderful idea! If we can get a credit card to switch Dasheroo to that would be great. Should we use yours Heidi? Or Erik Deck? Or Johns?

**Comment by heidiwiersma** [comment]
@lisaratner I'll work with John at add his.

**Comment by lisaratner** [comment]
Hey Heidi, is there a password the i-team usually uses? When I switch the username, I will also update the password.

**Comment by heidiwiersma** [comment]
Lisa,

Thanks for asking, please use InnovateLB

Please excuse the brevity, any spelling, or punctuation mistakes. Sent from my mobile device

On Aug 5, 2016, at 10:38 AM, Lisa Ratner <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Heidi, is there a password the i-team usually uses? When I switch the username, I will also update the password.

-

**Comment by rossettistone** [comment]
As this is an open-source repository, this and all conversation threads are public to the world.

The password above should be treated as compromised, and changed in all systems that use it.

Please do all future communication of secure information by other channels.

**Comment by lisaratner** [comment]
@heidiwiersma ^^ unfortunately we have to change all the accounts that use that password since waffle is an open source platform

**Comment by heidiwiersma** [comment]
Thanks to both of you for this valuable lesson!

**Comment by lisaratner** [comment]
Email john for details
